config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'auth/users/sessions',
      registrations: 'auth/users/registrations'
  }

  scope module: 'app' do
    resource :user, only: [:show, :edit] do
      collection do
        patch 'update_password'
      end
    end
    resources :projects do
      resources :entity_types do
        resources :entity_type_attributes
        resources :templates
        resources :operations do
          resources :downloads, only: [:create]
        end
      end
    end
    match '/help', to: 'pages#help', via: :get, as: :help
  end

  # https://hemamca.wordpress.com/2015/03/02/redirecting-to-custom-404-and-500-pages-in-rails/
  match '/404', to: 'app/pages#file_not_found', via: :all
  match '/422', to: 'app/pages#unprocessable', via: :all
  match '/500', to: 'app/pages#internal_server_error', via: :all


  # root to: 'app/pages#home'
  root to: 'app/projects#index'
end

app/views/app/ui/_app_name.html.erb
Docuply

app/views/app/ui/_empty_contents.html.erb
<!--<div class="<%#= 'pos-a' unless boxed %> t-0 l-0 w-100 h-100 d-f fxd-r fxw-w ai-c jc-c pos-r p-30">-->
<div class="t-0 l-0 w-100 h-100 d-f fxd-r fxw-w ai-c jc-c pos-r p-30">
  <% if img %>
    <div class="mR-60">
      <%= image_tag img, alt: '', height: '256px', width: '256px' %>
    </div>
  <% end %>

  <div class="d-f jc-c fxd-c">
    <h1 class="mB-30 fw-900 lh-1 c-red-500" style="font-size: 60px;"><%= lg_message %></h1>
    <h3 class="mB-10 fsz-lg c-grey-900"><%= md_message %></h3>
    <p class="mB-30 fsz-def c-grey-700">
      <%= sm_message %>
    </p>

    <% if button_text %>
      <div>
        <a href="<%= button_link %>" type="primary" class="btn btn-primary">
          <%= button_text %>
        </a>
      </div>
    <% end %>

  </div>
</div>

app/views/app/ui/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> ">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/app/ui/_header.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<title><%= render partial: 'app/ui/app_name' %> - <%= yield :title %></title>

<!-- Bootstrap core CSS -->
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<%#= stylesheet_pack_tag 'application', media: 'all' %>
<%#= javascript_pack_tag 'application' %>

app/views/app/ui/_topbar.html.erb
<!-- ### $Topbar ### -->
<div class="header navbar">
  <div class="header-container">
    <ul class="nav-left">
      <li>
        <a id='sidebar-toggle' class="sidebar-toggle" href="javascript:void(0);">
          <i class="ti-menu"></i>
        </a>
      </li>
      <li class="search-box">
        <a class="search-toggle no-pdd-right" href="javascript:void(0);">
          <i class="search-icon ti-search pdd-right-10"></i>
          <i class="search-icon-close ti-close pdd-right-10"></i>
        </a>
      </li>
      <li class="search-input">
        <input class="form-control" type="text" placeholder="Search...">
      </li>
    </ul>
    <ul class="nav-right">
      <li class="notifications dropdown">
<!--        <span class="counter bgc-red">3</span>-->
        <a href="" class="dropdown-toggle no-after" data-toggle="dropdown">
          <i class="ti-bell"></i>
        </a>

        <ul class="dropdown-menu">
          <li class="pX-20 pY-15 bdB">
            <i class="ti-bell pR-10"></i>
            <span class="fsz-sm fw-600 c-grey-900">Notifications</span>
          </li>
          <li class="pX-20 pY-15 ta-c bdT">
                    <span>
                      <a href="#" class="c-grey-600 cH-blue fsz-sm td-n">No new notifications
<!--                        <i class="ti-angle-right fsz-xs mL-10"></i>-->
                      </a>
                    </span>
          </li>
        </ul>
      </li>
      <li class="notifications dropdown">
<!--        <span class="counter bgc-blue">3</span>-->
        <a href="" class="dropdown-toggle no-after" data-toggle="dropdown">
          <i class="ti-email"></i>
        </a>

        <ul class="dropdown-menu">
          <li class="pX-20 pY-15 bdB">
            <i class="ti-email pR-10"></i>
            <span class="fsz-sm fw-600 c-grey-900">Messages</span>
          </li>
          <li class="pX-20 pY-15 ta-c bdT">
                    <span>
                      <a href="#" class="c-grey-600 cH-blue fsz-sm td-n">No new messages<i class="fs-xs ti-angle-right mL-10"></i></a>
                    </span>
          </li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1" data-toggle="dropdown">
          <div class="peer mR-10">
<!--            <img class="w-2r bdrs-50p" src="https://randomuser.me/api/portraits/lego/1.jpg" alt="">-->
            <%= image_tag 'user.png', class: 'w-3r bdrs-50p', alt: 'user' %>
          </div>
          <div class="peer">
            <span class="fsz-sm c-grey-900"><%= current_user.full_name %></span>
          </div>
        </a>
        <ul class="dropdown-menu fsz-sm">
<!--          <li>-->
<!--            <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">-->
<!--              <i class="ti-settings mR-10"></i>-->
<!--              <span>Setting</span>-->
<!--            </a>-->
<!--          </li>-->
          <li>
            <a href="<%= user_path %>" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
              <i class="ti-user mR-10"></i>
              <span>Account</span>
            </a>
          </li>
<!--          <li>-->
<!--            <a href="#" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">-->
<!--              <i class="ti-email mR-10"></i>-->
<!--              <span>Messages</span>-->
<!--            </a>-->
<!--          </li>-->
          <li role="separator" class="divider"></li>
          <li>
            <a href="<%= destroy_user_session_path %>"
               data-method="delete"
               class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
              <i class="ti-power-off mR-10"></i>
              <span>Logout</span>
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>