config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'auth/users/sessions',
      registrations: 'auth/users/registrations'
  }

  scope module: 'app' do
    resource :user, only: [:show, :edit] do
      collection do
        patch 'update_password'
      end
    end
    resources :projects do
      resources :entity_types do
        resources :entity_type_attributes
        resources :templates
        resources :operations do
          resources :downloads, only: [:create]
        end
      end
    end
    match '/help', to: 'pages#help', via: :get, as: :help
  end

  # https://hemamca.wordpress.com/2015/03/02/redirecting-to-custom-404-and-500-pages-in-rails/
  match '/404', to: 'app/pages#file_not_found', via: :all
  match '/422', to: 'app/pages#unprocessable', via: :all
  match '/500', to: 'app/pages#internal_server_error', via: :all


  # root to: 'app/pages#home'
  root to: 'app/projects#index'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :account
  has_many :entity_types, dependent: :destroy
  has_many :operations, dependent: :destroy

  validates :title, presence: true

  after_create :create_sole_entity_type


  def sole_entity_type
    self.entity_types.first
  end


  private


  def create_sole_entity_type
    self.entity_types.create(name: "data-type-#{self.id}")
  end
end

app/controllers/app/projects_controller.rb
class App::ProjectsController < App::BaseController
  before_action :find_project, only: [:show, :edit, :update, :destroy]


  def index
    @projects = current_account.projects
  end


  def show
  end


  def new
    @project = current_account.projects.new
  end


  def edit
    render 'new'
  end


  def create
    @project = current_account.projects.new(project_params)
    if @project.save
      flash[:success] = "Document added!"
      redirect_to @project
    else
      flash.now[:error] = @project.errors.full_messages.first
      render 'new'
    end
  end


  def update
    if @project.update_attributes(project_params)
      flash[:success] = "Updated!"
      redirect_to @project
    else
      flash.now[:error] = @project.errors.full_messages.first
      render 'new'
    end
  end


  def destroy
    if @project && @project.destroy
      flash[:success] = "Deleted!"
      redirect_to projects_path
    end
  end


  private


  def project_params
    params.require(:project).permit(:title, :description)
  end


  def find_project
    @project = current_account.projects.find(params[:id])
  end
end

app/helpers/app/projects_helper.rb
module App::ProjectsHelper
end

app/views/app/projects/index.html.erb
<%= render partial: 'app/ui/projects/sidebar',
           locals: {
               sub_menu_items:       nil,
               show_section_actions: true,
           }
%>

<% content_for :title do %>
  All documents
<% end %>

<% content_for :sub_section_title do %>
  All documents
<% end %>


<% if @projects.present? %>

<div class="d-flex flex-row flex-wrap">
  <% @projects.each do |project| %>
    <div class="col-12 col-md-5 p-0 mr-0 mr-md-4 mb-4">

      <div class="p-3 bgc-white p-20 bd project-item bxshd">
<!--        <a class="td-n peers fxw-nw mR-20 peer-greed c-grey-900"-->
        <a class="td-n  fxw-nw mR-20 peer-greed c-grey-900"
           href="<%= project_path(project) %>">
          <div class="peer">
            <span class="lh-1"><%= project.title %></span>
            <div class="text-muted">
              <br>
              <%= project.description || '&nbsp;'.html_safe %>
            </div>
          </div>
        </a>
      </div>

    </div>
  <% end %>
</div>

<% else %>

  <%= render partial: 'app/ui/empty_contents',
             locals:  {
                 lg_message:  '',
                 md_message:  'No documents added...',
                 sm_message:  '',
                 button_text: 'Create Document',
                 button_link: new_project_path,
                 img:         asset_path('empty.png'),
                 boxed:       false
             }
  %>

<% end %>

app/views/app/projects/new.html.erb
<%= render partial: 'app/ui/projects/sidebar',
           locals:  {
               sub_menu_items:       [@project.title],
               show_section_actions: @project.persisted? ? true : false,
           }
%>
<% content_for :title do %>
  <%= @project.persisted? ? "#{@project.title} | Edit" : 'Add new' %> document
<% end %>

<% content_for :sub_section_title do %>
  <%= @project.persisted? ? "Edit" : 'Add new' %> document
<% end %>

<div class="row">
  <div class="col-12 col-lg-8">
    <div class="bgc-white p-20 bd bxshd">
      <div  class="">
        <%= form_for @project do |f| %>
          <div class="form-group">
            <%= f.label :title, 'Title' %>
            <%= f.text_field :title, class: 'form-control', required: 'required' %>
          </div>
          <br>

          <div class="form-group">
            <%= f.label :description, 'Description' %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <br>
          <br>

          <div class="form-group row">
            <div class="col-12 col-md-6">
              <%= f.submit 'Save', class: 'btn btn-primary col-12 col-md-4 mb-3' %>
              <%= link_to 'Cancel',
                          @project.persisted? ? project_path(@project) : projects_path,
                          class: 'btn btn-danger col-12 col-md-4 mb-3' %>
            </div>
            <% if @project.persisted? %>
            <div class="col-12 col-md-6">
              <%= link_to 'Delete document',
                          project_path(@project),
                          method: :delete,
                          data: { confirm: 'Are you sure you want to delete this document?!' },
                          class: 'btn btn-outline-danger float-none float-md-right col-12' %>
            </div>
            <% end %>
          </div>
        <% end %>




      </div>
    </div>

  </div>
</div>

app/views/app/projects/show.html.erb
<%= render partial: 'app/ui/projects/sidebar',
           locals: {
               sub_menu_items: [@project.title],
               show_section_actions: true,
           }
%>

<% content_for :title do %>
  <%= @project.title %>
<% end %>

<% content_for :sub_section_title do %>
  Document overview
<% end %>


<div class="row mb-3">
  <div class="col-12">
    <div class="bgc-white p-20 bd bxshd "><h6 class="lh-1 c-grey-800"><%= @project.title %></h6>
      <div class="mT-30">
        <%= @project.description %>

        <% unless @project.sole_entity_type %>
          <%= render partial: 'app/ui/empty_contents',
                     locals: {
                         lg_message: '',
                         md_message: 'Almost there...',
                         sm_message: 'Finish setting up this document by adding a data type and one or more templates.',
                         button_text: 'Add a data type',
                         button_link: new_project_entity_type_path(@project),
                         img: asset_path('almost.png'),
                         boxed: true
                     }
          %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if @project.sole_entity_type %>
  <div class="row">

    <div id="section-templates" class="col-12 mb-3">
      <div class="bxshd bgc-white p-20 bd">
        <h6 class="lh-1 c-grey-900">Templates</h6>

        <% templates = @project.sole_entity_type.templates %>
        <% if templates.present? %>
          <div class="row">
            <div class="col">
              <div class="table-responsive">
                <table class="table nbd">
                  <thead>
                  <tr>
                    <th class="bdwT-0 c-grey-900">Name</th>
                    <th class="bdwT-0 c-grey-900">Placeholders</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% templates.each do |template| %>
                    <tr>
                      <td>
                        <i class="mR-10 ti-file"></i>
                        <%= template.name %>
                      </td>
                      <td>
                        <div style="min-height:80px;">
                          <% placeholders = template.registered_placeholders %>
                          <% if placeholders.present? %>
                            <% placeholders.each do |placeholder| %>
                              <i> <%= placeholder %> </i><br>
                            <% end %>
                          <% else %>
                            <i>No placeholders found</i>
                          <% end %>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div> <!--          row-->
        <% else %>
          <%= render partial: 'app/ui/empty_contents',
                     locals: {
                         lg_message: '1.',
                         md_message: 'Templates',
                         sm_message: 'Prepare and upload templates',
                         button_text: 'Add a template',
                         button_link: new_project_entity_type_template_path(
                             @project, @project.sole_entity_type),
                         img: nil,
                         boxed: true
                     }
          %>
        <% end %>

      </div>
    </div> <!--  section-templates-->

    <div id="section-placeholders" class="col-12">
      <div class="bxshd bgc-white p-20 bd">
        <h6 class="lh-1 c-grey-900">Placeholders</h6>

        <% if @project.sole_entity_type.placeholder_attributes.present? %>

          <div class="row">
            <div class="col">

              <div class="table-responsive">
                <table class="table nbd">
                  <thead>
                  <tr>
                    <th class="bdwT-0 c-grey-900">Name</th>
                    <th class="bdwT-0 c-grey-900">Tag</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @project.sole_entity_type.placeholder_attributes.each do |attribute| %>
                    <tr>
                      <td>
                        <i class="mR-10 ti-target"></i>
                        <%= attribute.name %></td>
                      <td><i><%= attribute.var_name %></i></td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>

            </div> <!--            col-->
          </div> <!--          row-->

        <% else %>

          <%= render partial: 'app/ui/empty_contents',
                     locals: {
                         lg_message: 2,
                         md_message: 'Placeholders',
                         sm_message: 'Specify placeholders in templates',
                         button_text: 'Add a placeholder',
                         button_link: new_project_entity_type_entity_type_attribute_path(
                             @project,
                             @project.sole_entity_type),
                         img: nil,
                         boxed: true,
                     }
          %>

        <% end %>

      </div>
    </div> <!--    section-placeholders-->


<% end %>